[project]
name = "transferscore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
authors = [
  { name = "Lucas Jerry", email = "lucasjerry@gmail.com" },
]
dependencies = [
    "flask>=3.1.1",
]
